import dayjs from 'dayjs'
import isBetween from 'dayjs/plugin/isBetween.js'
import isSameOrAfter from 'dayjs/plugin/isSameOrAfter.js'
import isSameOrBefore from 'dayjs/plugin/isSameOrBefore.js'
import localeData from 'dayjs/plugin/localeData.js'
import minMax from 'dayjs/plugin/minMax.js'
import timezone from 'dayjs/plugin/timezone.js'
import utc from 'dayjs/plugin/utc.js'
import weekday from 'dayjs/plugin/weekday.js'
import weekOfYear from 'dayjs/plugin/weekOfYear.js'

// Extend dayjs with plugins
dayjs.extend(weekday)
dayjs.extend(weekOfYear)
dayjs.extend(isSameOrAfter)
dayjs.extend(isSameOrBefore)
dayjs.extend(isBetween)
dayjs.extend(minMax)
dayjs.extend(timezone)
dayjs.extend(utc)
dayjs.extend(localeData)

// Import all dayjs locales alphabetically
// locale.json file: [{"key":"af","name":"Afrikaans"},{"key":"am","name":"Amharic"},{"key":"ar-dz","name":"Arabic (Algeria)"},{"key":"ar-iq","name":" Arabic (Iraq)"},{"key":"ar-kw","name":"Arabic (Kuwait)"},{"key":"ar-ly","name":"Arabic (Lybia)"},{"key":"ar-ma","name":"Arabic (Morocco)"},{"key":"ar-sa","name":"Arabic (Saudi Arabia)"},{"key":"ar-tn","name":" Arabic (Tunisia)"},{"key":"ar","name":"Arabic"},{"key":"az","name":"Azerbaijani"},{"key":"be","name":"Belarusian"},{"key":"bg","name":"Bulgarian"},{"key":"bi","name":"Bislama"},{"key":"bm","name":"Bambara"},{"key":"bn-bd","name":"Bengali (Bangladesh)"},{"key":"bn","name":"Bengali"},{"key":"bo","name":"Tibetan"},{"key":"br","name":"Breton"},{"key":"bs","name":"Bosnian"},{"key":"ca","name":"Catalan"},{"key":"cs","name":"Czech"},{"key":"cv","name":"Chuvash"},{"key":"cy","name":"Welsh"},{"key":"de-at","name":"German (Austria)"},{"key":"da","name":"Danish"},{"key":"de-ch","name":"German (Switzerland)"},{"key":"de","name":"German"},{"key":"dv","name":"Maldivian"},{"key":"el","name":"Greek"},{"key":"en-au","name":"English (Australia)"},{"key":"en-ca","name":"English (Canada)"},{"key":"en-gb","name":"English (United Kingdom)"},{"key":"en-ie","name":"English (Ireland)"},{"key":"en-il","name":"English (Israel)"},{"key":"en-in","name":"English (India)"},{"key":"en-nz","name":"English (New Zealand)"},{"key":"en-sg","name":"English (Singapore)"},{"key":"en-tt","name":"English (Trinidad & Tobago)"},{"key":"eo","name":"Esperanto"},{"key":"en","name":"English"},{"key":"es-do","name":"Spanish (Dominican Republic)"},{"key":"es-mx","name":"Spanish (Mexico)"},{"key":"es-pr","name":"Spanish (Puerto Rico)"},{"key":"es-us","name":"Spanish (United States)"},{"key":"et","name":"Estonian"},{"key":"es","name":"Spanish"},{"key":"eu","name":"Basque"},{"key":"fa","name":"Persian"},{"key":"fo","name":"Faroese"},{"key":"fi","name":"Finnish"},{"key":"fr-ca","name":"French (Canada)"},{"key":"fr-ch","name":"French (Switzerland)"},{"key":"fr","name":"French"},{"key":"fy","name":"Frisian"},{"key":"ga","name":"Irish or Irish Gaelic"},{"key":"gd","name":"Scottish Gaelic"},{"key":"gom-latn","name":"Konkani Latin script"},{"key":"gl","name":"Galician"},{"key":"gu","name":"Gujarati"},{"key":"he","name":"Hebrew"},{"key":"hi","name":"Hindi"},{"key":"hr","name":"Croatian"},{"key":"hu","name":"Hungarian"},{"key":"ht","name":"Haitian Creole (Haiti)"},{"key":"hy-am","name":"Armenian"},{"key":"id","name":"Indonesian"},{"key":"is","name":"Icelandic"},{"key":"it-ch","name":"Italian (Switzerland)"},{"key":"it","name":"Italian"},{"key":"ja","name":"Japanese"},{"key":"jv","name":"Javanese"},{"key":"ka","name":"Georgian"},{"key":"kk","name":"Kazakh"},{"key":"km","name":"Cambodian"},{"key":"kn","name":"Kannada"},{"key":"ko","name":"Korean"},{"key":"ku","name":"Kurdish"},{"key":"ky","name":"Kyrgyz"},{"key":"lb","name":"Luxembourgish"},{"key":"lo","name":"Lao"},{"key":"lt","name":"Lithuanian"},{"key":"lv","name":"Latvian"},{"key":"me","name":"Montenegrin"},{"key":"mi","name":"Maori"},{"key":"mk","name":"Macedonian"},{"key":"ml","name":"Malayalam"},{"key":"mn","name":"Mongolian"},{"key":"mr","name":"Marathi"},{"key":"ms-my","name":"Malay"},{"key":"ms","name":"Malay"},{"key":"mt","name":"Maltese (Malta)"},{"key":"my","name":"Burmese"},{"key":"nb","name":"Norwegian Bokmål"},{"key":"ne","name":"Nepalese"},{"key":"nl-be","name":"Dutch (Belgium)"},{"key":"nl","name":"Dutch"},{"key":"pl","name":"Polish"},{"key":"pt-br","name":"Portuguese (Brazil)"},{"key":"pt","name":"Portuguese"},{"key":"rn","name":"Kirundi"},{"key":"ro","name":"Romanian"},{"key":"ru","name":"Russian"},{"key":"rw","name":"Kinyarwanda (Rwanda)"},{"key":"sd","name":"Sindhi"},{"key":"se","name":"Northern Sami"},{"key":"si","name":"Sinhalese"},{"key":"sk","name":"Slovak"},{"key":"sl","name":"Slovenian"},{"key":"sq","name":"Albanian"},{"key":"sr-cyrl","name":"Serbian Cyrillic"},{"key":"ss","name":"siSwati"},{"key":"sv-fi","name":"Finland Swedish"},{"key":"sr","name":"Serbian"},{"key":"sv","name":"Swedish"},{"key":"sw","name":"Swahili"},{"key":"ta","name":"Tamil"},{"key":"te","name":"Telugu"},{"key":"tet","name":"Tetun Dili (East Timor)"},{"key":"tg","name":"Tajik"},{"key":"th","name":"Thai"},{"key":"tk","name":"Turkmen"},{"key":"tl-ph","name":"Tagalog (Philippines)"},{"key":"tlh","name":"Klingon"},{"key":"tr","name":"Turkish"},{"key":"tzl","name":"Talossan"},{"key":"tzm-latn","name":"Central Atlas Tamazight Latin"},{"key":"tzm","name":"Central Atlas Tamazight"},{"key":"ug-cn","name":"Uyghur (China)"},{"key":"uk","name":"Ukrainian"},{"key":"ur","name":"Urdu"},{"key":"uz-latn","name":"Uzbek Latin"},{"key":"uz","name":"Uzbek"},{"key":"vi","name":"Vietnamese"},{"key":"x-pseudo","name":"Pseudo"},{"key":"yo","name":"Yoruba Nigeria"},{"key":"zh-cn","name":"Chinese (China)"},{"key":"zh-hk","name":"Chinese (Hong Kong)"},{"key":"zh-tw","name":"Chinese (Taiwan)"},{"key":"zh","name":"Chinese"},{"key":"oc-lnc","name":"Occitan, lengadocian dialecte"},{"key":"nn","name":"Nynorsk"},{"key":"pa-in","name":"Punjabi (India)"}]
import 'dayjs/locale/af.js'
import 'dayjs/locale/am.js'
import 'dayjs/locale/ar-dz.js'
import 'dayjs/locale/ar-iq.js'
import 'dayjs/locale/ar-kw.js'
import 'dayjs/locale/ar-ly.js'
import 'dayjs/locale/ar-ma.js'
import 'dayjs/locale/ar-sa.js'
import 'dayjs/locale/ar-tn.js'
import 'dayjs/locale/ar.js'
import 'dayjs/locale/az.js'
import 'dayjs/locale/be.js'
import 'dayjs/locale/bg.js'
import 'dayjs/locale/bi.js'
import 'dayjs/locale/bm.js'
import 'dayjs/locale/bn-bd.js'
import 'dayjs/locale/bn.js'
import 'dayjs/locale/bo.js'
import 'dayjs/locale/br.js'
import 'dayjs/locale/bs.js'
import 'dayjs/locale/ca.js'
import 'dayjs/locale/cs.js'
import 'dayjs/locale/cv.js'
import 'dayjs/locale/cy.js'
import 'dayjs/locale/da.js'
import 'dayjs/locale/de-at.js'
import 'dayjs/locale/de-ch.js'
import 'dayjs/locale/de.js'
import 'dayjs/locale/dv.js'
import 'dayjs/locale/el.js'
import 'dayjs/locale/en-au.js'
import 'dayjs/locale/en-ca.js'
import 'dayjs/locale/en-gb.js'
import 'dayjs/locale/en-ie.js'
import 'dayjs/locale/en-il.js'
import 'dayjs/locale/en-in.js'
import 'dayjs/locale/en-nz.js'
import 'dayjs/locale/en-sg.js'
import 'dayjs/locale/en-tt.js'
import 'dayjs/locale/en.js'
import 'dayjs/locale/eo.js'
import 'dayjs/locale/es-do.js'
import 'dayjs/locale/es-mx.js'
import 'dayjs/locale/es-pr.js'
import 'dayjs/locale/es-us.js'
import 'dayjs/locale/es.js'
import 'dayjs/locale/et.js'
import 'dayjs/locale/eu.js'
import 'dayjs/locale/fa.js'
import 'dayjs/locale/fi.js'
import 'dayjs/locale/fo.js'
import 'dayjs/locale/fr-ca.js'
import 'dayjs/locale/fr-ch.js'
import 'dayjs/locale/fr.js'
import 'dayjs/locale/fy.js'
import 'dayjs/locale/ga.js'
import 'dayjs/locale/gd.js'
import 'dayjs/locale/gl.js'
import 'dayjs/locale/gom-latn.js'
import 'dayjs/locale/gu.js'
import 'dayjs/locale/he.js'
import 'dayjs/locale/hi.js'
import 'dayjs/locale/hr.js'
import 'dayjs/locale/ht.js'
import 'dayjs/locale/hu.js'
import 'dayjs/locale/hy-am.js'
import 'dayjs/locale/id.js'
import 'dayjs/locale/is.js'
import 'dayjs/locale/it-ch.js'
import 'dayjs/locale/it.js'
import 'dayjs/locale/ja.js'
import 'dayjs/locale/jv.js'
import 'dayjs/locale/ka.js'
import 'dayjs/locale/kk.js'
import 'dayjs/locale/km.js'
import 'dayjs/locale/kn.js'
import 'dayjs/locale/ko.js'
import 'dayjs/locale/ku.js'
import 'dayjs/locale/ky.js'
import 'dayjs/locale/lb.js'
import 'dayjs/locale/lo.js'
import 'dayjs/locale/lt.js'
import 'dayjs/locale/lv.js'
import 'dayjs/locale/me.js'
import 'dayjs/locale/mi.js'
import 'dayjs/locale/mk.js'
import 'dayjs/locale/ml.js'
import 'dayjs/locale/mn.js'
import 'dayjs/locale/mr.js'
import 'dayjs/locale/ms-my.js'
import 'dayjs/locale/ms.js'
import 'dayjs/locale/mt.js'
import 'dayjs/locale/my.js'
import 'dayjs/locale/nb.js'
import 'dayjs/locale/ne.js'
import 'dayjs/locale/nl-be.js'
import 'dayjs/locale/nl.js'
import 'dayjs/locale/nn.js'
import 'dayjs/locale/oc-lnc.js'
import 'dayjs/locale/pa-in.js'
import 'dayjs/locale/pl.js'
import 'dayjs/locale/pt-br.js'
import 'dayjs/locale/pt.js'
import 'dayjs/locale/rn.js'
import 'dayjs/locale/ro.js'
import 'dayjs/locale/ru.js'
import 'dayjs/locale/rw.js'
import 'dayjs/locale/sd.js'
import 'dayjs/locale/se.js'
import 'dayjs/locale/si.js'
import 'dayjs/locale/sk.js'
import 'dayjs/locale/sl.js'
import 'dayjs/locale/sq.js'
import 'dayjs/locale/sr-cyrl.js'
import 'dayjs/locale/sr.js'
import 'dayjs/locale/ss.js'
import 'dayjs/locale/sv-fi.js'
import 'dayjs/locale/sv.js'
import 'dayjs/locale/sw.js'
import 'dayjs/locale/ta.js'
import 'dayjs/locale/te.js'
import 'dayjs/locale/tet.js'
import 'dayjs/locale/tg.js'
import 'dayjs/locale/th.js'
import 'dayjs/locale/tk.js'
import 'dayjs/locale/tl-ph.js'
import 'dayjs/locale/tlh.js'
import 'dayjs/locale/tr.js'
import 'dayjs/locale/tzl.js'
import 'dayjs/locale/tzm-latn.js'
import 'dayjs/locale/tzm.js'
import 'dayjs/locale/ug-cn.js'
import 'dayjs/locale/uk.js'
import 'dayjs/locale/ur.js'
import 'dayjs/locale/uz-latn.js'
import 'dayjs/locale/uz.js'
import 'dayjs/locale/vi.js'
import 'dayjs/locale/x-pseudo.js'
import 'dayjs/locale/yo.js'
import 'dayjs/locale/zh-cn.js'
import 'dayjs/locale/zh-hk.js'
import 'dayjs/locale/zh-tw.js'
import 'dayjs/locale/zh.js'

export default dayjs
